---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shinyproxy-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-sa-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: shinyproxy-sa
roleRef:
  kind: Role
  name: shinyproxy-sa-role
  apiGroup: rbac.authorization.k8s.io
