apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: shinyproxy-operator-build
spec:
  containers:
    - name: shinyproxy-operator-build
      image: public.ecr.aws/docker/library/maven:3-eclipse-temurin-17-focal
      command:
        - cat
      tty: true
      resources:
       requests:
         memory: "2Gi"
         cpu: "1.0"
       limits:
         memory: "4Gi"
         cpu: "1.5"
