apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    namespace: replace_this_namespace
    releaseName: redis
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      global:
        redis:
          password: abc
      sentinel:
        enabled: true
        masterSet: shinyproxy
    version: 17.3.14

patches:
  - patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1managed-by
      - op: remove
        path: /metadata/labels/helm.sh~1chart
      - op: remove
        path: /metadata/namespace
    target:
      name: .*
