---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skipper-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skipper-ingress
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - zalando.org
    resources:
      - routegroups
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skipper-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skipper-ingress
subjects:
  - kind: ServiceAccount
    name: skipper-ingress
