{
 "title": "ShinyProxy App Resources",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appInfo, proxy_namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\"}, user_id)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\"}, spec_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(appInfo{job=~\".+\", proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\"}, proxy_instance)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\"}, proxy_id)"
    }
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard shows the resources (CPU and memory) consumed by apps.\n\n**Tips:**\n\n- use the filters on the top of page\n- the app metadata is only shown when a single id is selected\n- change the time range in the top-right corner of the page\n- disable the automatic refresh (in the top-right corner) if the dashboard takes a long time to load\n- when the time range exceeds 7 days, the dashboard might fail to load the data\n- use the calendar button (in the time range selector) to load data on specific dates or times\n- select a single id to view the exact values \n- some panels might be empty when an app fails to startup or crashes shortly (1-2 minutes) after startup"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "App creation time",
   "type": "stat",
   "description": "The time the user launched the application. Only shown if a single id is selected. ",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (proxy_created_timestamp)"
    }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "description": "The name of the user that launched the app. Only shown if a single id is selected. ",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (user_id)"
    }
   ]
  },
  {
   "title": "App",
   "type": "stat",
   "description": "The id of the application spec. Only shown if a single id is selected. ",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (spec_id)"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "The name of the instance. By default this is `_`. When a user can start multiple instances of the same app, this is the name chosen by the user. Only shown if a single id is selected. ",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (proxy_instance)"
    }
   ]
  },
  {
   "title": "App status",
   "type": "stat",
   "description": "The status of the app. It can take up to two minutes for the status to change. Only shown if a single id is selected. ",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The CPU usage of an app. The requests and limits are summed for all instances. Select a single id to view the exact requests and limits for an app.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}[5m])",
     "legendFormat": "CPU Usage {{container_label_openanalytics_eu_sp_proxy_id}}"
    },
    {
     "expr": "container_spec_cpu_quota{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"} / 100000",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "description": "The CPU throttling of an app. An app is throttled when it tries to user more CPU resources than allowed by the `container-cpu-limit` setting. If no `container-cpu-limit` is configured, the panel will show the text `No data`.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}[$__rate_interval])) /sum(increase(container_cpu_cfs_periods_total{container_label_openanalytics_eu_sp_proxy_id=\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}[$__rate_interval]))",
     "legendFormat": "CPU Throttling {{container_label_openanalytics_eu_sp_proxy_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "description": "The memory usage of an app. The requests and limits are summed for all instances. Select a single id to view the exact requests and limits for an app.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "Memory Usage {{container_label_openanalytics_eu_sp_proxy_id}}"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"} > 0)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"} > 0)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Total network traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "Receive {{container_label_openanalytics_eu_sp_proxy_id}}"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "Transmit {{container_label_openanalytics_eu_sp_proxy_id}}"
    }
   ]
  }
 ]
}