{
 "title": "ShinyProxy Aggregated Usage",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(absolute_users_logged_in{shinyproxy_realm=~\".+\"}, namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(absolute_users_logged_in{namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(absolute_users_logged_in{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\"}, shinyproxy_instance)"
    }
   },
   {
    "name": "spec_id",
    "label": "app",
    "query": {
     "query": "label_values(absolute_apps_running{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\"}, spec_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard shows the aggregated usage of ShinyProxy.\n\n**Tips:**\n\n- use the filters on the top of page\n- change the time range in the top-right corner of the page\n- disable the automatic refresh (in the top-right corner) if the dashboard takes a long time to load"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "App starts",
   "type": "table",
   "description": "The number of times an app has been started. Does not include currently running apps (only apps that haven been stopped).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(usageTime_seconds_count{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__range])) by (spec_id,shinyproxy_realm) "
    }
   ]
  },
  {
   "title": "Total App Usage",
   "type": "table",
   "description": "The total time an app has been running. Combines all instances of an app of all users. Does not include currently running apps (only apps that haven been stopped).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(usageTime_seconds_sum{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__range])) by (spec_id,shinyproxy_realm) "
    }
   ]
  },
  {
   "title": "Average App Usage",
   "type": "table",
   "description": "The average time an app instance runs. This is the average of all instances of an app of all users. Does not include currently running apps (only apps that haven been stopped).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(usageTime_seconds_sum{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__range])) by (spec_id,shinyproxy_realm) / clamp_min(sum(increase(usageTime_seconds_count{namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",shinyproxy_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__range])) by (spec_id,shinyproxy_realm), 1)"
    }
   ]
  }
 ]
}