{
 "title": "ShinyProxy Delegate App Logs",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(delegate_app_info, proxy_namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(delegate_app_info{job=~\".+\",proxy_namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(delegate_app_info{job=~\".+\",proxy_namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\"}, spec_id)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(delegate_app_info{job=~\".+\",proxy_namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",spec_id=~\"$app\"}, proxy_id)"
    }
   },
   { "name": "datasource", "query": "loki" },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "App creation time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delegate_app_info{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", spec_id=~\"$app\", proxy_id=\"$id\"}) by (proxy_created_timestamp)"
    }
   ]
  },
  {
   "title": "App",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delegate_app_info{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", spec_id=~\"$app\", proxy_id=\"$id\"}) by (spec_id)"
    }
   ]
  },
  {
   "title": "App status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delegate_app_info{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", spec_id=~\"$app\", proxy_id=\"$id\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{sp_realm_id=~\".+\", namespace=~\"$namespace\", sp_realm_id=~\"$realm\", sp_spec_id=~\"$app\", sp_proxy_id=\"$id\", sp_proxy_id!=\"\"} | line_format `[App]: {{ __line__ }}` "
    },
    {
     "expr": "{app=\"shinyproxy\", namespace=~\"$namespace\", sp_realm_id=~\"$realm\"} | json | delegateProxyId!=\"\" | delegateProxyId=\"$id\" | line_format `[ShinyProxy] {{.level}}: {{.message}} {{.stack_trace}}`"
    },
    {
     "expr": "{app=\"shinyproxy\", namespace=~\"$namespace\", sp_realm_id=~\"$realm\"} | json | proxyId!=\"\" | proxyId=\"$id\" | line_format `[ShinyProxy] {{.level}}: {{.message}} {{.stack_trace}}`"
    }
   ]
  }
 ]
}