{
 "title": "ShinyProxy App Logs",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appInfo, proxy_namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\"}, user_id)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\"}, spec_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(appInfo{job=~\".+\", proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\"}, proxy_instance)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\"}, proxy_id)"
    }
   },
   { "name": "datasource", "query": "loki" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "App creation time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (proxy_created_timestamp)"
    }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (user_id)"
    }
   ]
  },
  {
   "title": "App",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (spec_id)"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}) by (proxy_instance)"
    }
   ]
  },
  {
   "title": "App status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appInfo{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", user_id=~\"$user\", spec_id=~\"$app\", proxy_instance=~\"$instance\", proxy_id=\"$id\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{sp_realm_id=~\".+\", namespace=~\"$namespace\", sp_realm_id=~\"$realm\", sp_proxy_id=~\"$id\", sp_proxy_id!=\"\"} | line_format `[App]: {{ __line__ }}` |~ `(?i)$filter`"
    },
    {
     "expr": "{app=\"shinyproxy\", sp_realm_id=~\"$realm\"} | json | proxyId!=\"\" | proxyId=~\"$id\" | line_format `[ShinyProxy] {{.level}}: {{.message}} {{.stack_trace}}` |~ `(?i)$filter`"
    }
   ]
  }
 ]
}