{
 "title": "ShinyProxy Delegate App Resources",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(delegate_app_status, proxy_namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(delegate_app_status{job=~\".+\",proxy_namespace=~\"$namespace\"}, shinyproxy_realm)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(delegate_app_status{job=~\".+\",proxy_namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\"}, spec_id)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(delegate_app_status{job=~\".+\",proxy_namespace=~\"$namespace\",shinyproxy_realm=~\"$realm\",spec_id=~\"$app\"}, proxy_id)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "App creation time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delegate_app_status{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", spec_id=~\"$app\", proxy_id=\"$id\"}) by (proxy_created_timestamp)"
    }
   ]
  },
  {
   "title": "App",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delegate_app_status{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", spec_id=~\"$app\", proxy_id=\"$id\"}) by (spec_id)"
    }
   ]
  },
  {
   "title": "App status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delegate_app_status{job=~\".+\",proxy_namespace=~\"$namespace\", shinyproxy_realm=~\"$realm\", spec_id=~\"$app\", proxy_id=\"$id\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}[5m])) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "CPU Usage {{container_label_openanalytics_eu_sp_proxy_id}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"} / 100000)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}[$__rate_interval])) by (container_label_openanalytics_eu_sp_proxy_id) / sum(increase(container_cpu_cfs_periods_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}[$__rate_interval])) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "CPU Throttling {{container_label_openanalytics_eu_sp_proxy_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "Memory Usage {{container_label_openanalytics_eu_sp_proxy_id}}"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"} > 0)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"} > 0)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Total network traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "Receive {{container_label_openanalytics_eu_sp_proxy_id}}"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{container_label_openanalytics_eu_sp_proxy_id=~\"$id\",container_label_openanalytics_eu_sp_proxy_id!=\"\"}) by (container_label_openanalytics_eu_sp_proxy_id)",
     "legendFormat": "Transmit {{container_label_openanalytics_eu_sp_proxy_id}}"
    }
   ]
  }
 ]
}